name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    name: Format (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure


  tests:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    needs: format
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install --group tests
      - name: Run pytest
        run: uv run pytest -q
